apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: our-redis-stack-server
  name: our-redis-stack-server
spec:
  containers:
  - image: redis/redis-stack-server
    name: our-redis-stack-server
    command: ["/opt/custom-entry/custom-entrypoint.sh"]
    ports:
    - containerPort: 6379
    resources: {}
    volumeMounts:
      - name: custom-entry-volume
        mountPath: /opt/custom-entry
  volumes:
    - name: custom-entry-volume
      configMap:
        name: custom-entrypoint
        items:
          - key: custom-entrypoint.sh
            path: custom-entrypoint.sh
        defaultMode: 0755
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
