# This is a basic workflow to help you get started with Actions
name: Go CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Check out code to GOPATH
        uses: actions/checkout@v2
      # Sets up the Go environment
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      # Runs Go Lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
